#include <usart.h>
extern uint8_t rxData[10];

void uart1Init(uint32_t speed) {
	//GPIO: PA9-Tx, PA10-Rx
	SET_BIT(RCC->AHBENR, RCC_AHBENR_GPIOAEN);

	GPIOA->AFR[1] |= 0x01 << GPIO_AFRH_AFRH1_Pos;
	GPIOA->AFR[1] |= 0x01 << GPIO_AFRH_AFRH2_Pos;
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER9_Msk, 0b10<<GPIO_MODER_MODER9_Pos);
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER10_Msk, 0b10<<GPIO_MODER_MODER10_Pos);
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEEDR9_Msk, 0b11<<GPIO_OSPEEDR_OSPEEDR9_Pos);
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEEDR10_Msk, 0b11<<GPIO_OSPEEDR_OSPEEDR10_Pos);
	MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPDR9_Msk, 0b01<<GPIO_PUPDR_PUPDR9_Pos);
	MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPDR10_Msk, 0b01<<GPIO_PUPDR_PUPDR10_Pos);

	//USART
	SET_BIT(RCC->APB2ENR, RCC_APB2ENR_USART1EN);

	CLEAR_BIT(DMA1_Channel2->CCR, DMA_CCR_EN);
	SET_BIT(USART1->CR3, USART_CR3_DMAT);
	SET_BIT(USART1->CR3, USART_CR3_DMAR);
	//SET_BIT(USART1->CR1, USART_CR1_TCIE);
	//SET_BIT(USART1->CR1, USART_CR1_TXEIE);

	USART1->RTOR = 115200; // При скорости 115200 это 1 секунда
	SET_BIT(USART1->CR1, USART_CR1_RTOIE);
	SET_BIT(USART1->CR2, USART_CR2_RTOEN);
	NVIC_EnableIRQ(USART1_IRQn);

	USART1->BRR = 48000000 / speed;

	SET_BIT(USART1->CR1, USART_CR1_RE);
	SET_BIT(USART1->CR1, USART_CR1_TE);
	SET_BIT(USART1->CR1, USART_CR1_UE);

	//DMA Rx
	SET_BIT(RCC->AHBENR, RCC_AHBENR_DMA1EN);

	DMA1_Channel3->CPAR = (uint32_t)(&(USART1->RDR));
	SET_BIT(DMA1_Channel3->CCR, DMA_CCR_CIRC);
	SET_BIT(DMA1_Channel3->CCR, DMA_CCR_MINC);

	//DMA Tx
	DMA1_Channel2->CPAR = (uint32_t) (&(USART1->TDR));
	SET_BIT(DMA1_Channel2->CCR, DMA_CCR_DIR);
	SET_BIT(DMA1_Channel2->CCR, DMA_CCR_MINC);

	SET_BIT(DMA1_Channel3->CCR, DMA_CCR_TCIE);
	SET_BIT(DMA1_Channel3->CCR, DMA_CCR_HTIE);
	NVIC_EnableIRQ(DMA1_Channel2_3_IRQn);
}

void uart1TxDma(uint8_t *dmaTxMemAddr, uint32_t TxBuffSize) {
	CLEAR_BIT(DMA1_Channel2->CCR, DMA_CCR_EN);
	DMA1_Channel2->CMAR = (uint32_t) (dmaTxMemAddr);
	DMA1_Channel2->CNDTR = TxBuffSize;
	SET_BIT(DMA1_Channel2->CCR, DMA_CCR_EN);
}
void uart1RxDma(uint8_t *dmaRxMemAddr, uint32_t RxBuffSize) {
	DMA1_Channel3->CMAR = (uint32_t)(dmaRxMemAddr);
	DMA1_Channel3->CNDTR = RxBuffSize;
	SET_BIT(DMA1_Channel3->CCR, DMA_CCR_EN);
}
